name: hello-world
on: push
jobs:
  hello-world-job:
    run-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"

      - name: use node.js
        uses: actions@setup-node@v3
        with:
          node-version: '18.x'
      -  runs: npm install
      -  runs: npm run build
        
